---
settings:
  name: BlueXP volume caching
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: es-es,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,fr-fr,it-it
sidebar:
  entries:
  - title: Documentos sobre el almacenamiento en caché de volúmenes de BlueXP
    url: "/index.html"
  - section: release-notes
  - section: get-started
  - section: use
  - section: support
  - title: Avisos legales
    url: "/legal-notices.html"
product-family:
  name: BlueXP
  repo: bluexp-family
  sidebar_label: Toda la documentación de BlueXP
