---
sidebar: sidebar 
permalink: use/cache-manage.html 
keywords: volume caching, bluexp volume caching 
summary: El almacenamiento en caché de volúmenes proporciona un volumen persistente y editable en un lugar remoto. Puede usar el almacenamiento en caché de volúmenes de BlueXP para acelerar el acceso a los datos o para descargar el tráfico de volúmenes con un acceso frecuente. Los volúmenes de caché son ideales para las cargas de trabajo de lectura intensiva, especialmente cuando los clientes necesitan acceder a los mismos datos de manera repetida. 
---
= Gestionar una caché
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede editar una caché, cambiar la política de exportación, cambiar el tamaño de una caché y suprimir una caché.

Con el almacenamiento en caché de volúmenes de BlueXP, puedes lograr estos objetivos:

* Ver detalles de caché.
* Asigne una política de exportación diferente a una caché.
* Edite el almacenamiento en caché de un volumen y cambie su tamaño, etc. Editar tendrá la opción de ver y cambiar otras propiedades, y se agregarán más propiedades en edición en las próximas versiones.
* Cambie el tamaño de una caché existente en función de un porcentaje del tamaño del volumen original.
* Suprimir una caché.




== Ver detalles de caché

Para cada almacenamiento en caché, puede ver el volumen original, el entorno de trabajo, el volumen de la caché, y más.

.Pasos
. En la navegación de la izquierda de BlueXP, selecciona *Mobility* > *Volume caching*.
+
Es posible ver la lista de volúmenes de caché creados en el entorno de destino. La lista de cachés muestra los detalles de la caché.

. Para filtrar la lista, seleccione la opción *Filtrar por +*.
. Selecciona una fila y selecciona la opción *Acciones …* a la derecha.
. Selecciona *Ver y editar detalles*.
. Revise los detalles.




== Editar una caché

Es posible cambiar el nombre, el tamaño del volumen y la política de exportación de una caché.

.Pasos
. En la navegación de la izquierda de BlueXP, selecciona *Mobility* > *Volume caching*.
. Selecciona una fila y selecciona la opción *Acciones …* a la derecha.
. Selecciona *Ver y editar detalles*.
. En la pestaña Configuración básica, opcionalmente, cambie el nombre de caché y el tamaño del volumen de caché.
. Opcionalmente, expanda la pestaña Acceso de caché y modifique estos valores:
+
.. La ruta de montaje.
.. Una política de exportación diferente de la existente.


. Para cambiar los detalles de los recursos compartidos SMB/CIFS o las reglas de las políticas de exportación, haga clic en la opción para acceder a BlueXP System Manager.
. Seleccione *Guardar*.




== Asigne una política de exportación de caché diferente

Puede asignar una política de exportación diferente a una caché.

Las reglas de política de exportación de origen deben aplicarse al clúster de destino.


TIP: Puede asignar una política de exportación existente a una caché. No se pueden cambiar las reglas de las políticas de exportación. Si necesita cambiar las políticas de exportación, puede usar NetApp System Manager.

.Pasos
. En la navegación de la izquierda de BlueXP, selecciona *Mobility* > *Volume caching*.
. Selecciona una fila y selecciona la opción *Acciones …* a la derecha.
. Seleccione *Cambiar política de exportación*.
. Seleccione la política de exportación que desea asignar a la caché.
. Seleccione *Guardar*.




== Cambiar el tamaño de una caché

Es posible cambiar el tamaño del volumen de caché según un porcentaje del volumen de origen.

.Pasos
. En la navegación de la izquierda de BlueXP, selecciona *Mobility* > *Volume caching*.
. Selecciona una fila y selecciona la opción *Acciones …* a la derecha.
. Selecciona *Cambiar tamaño*.
. Introduzca un nuevo porcentaje del tamaño del volumen de origen.
+
El tamaño del volumen de caché cambiará al nuevo porcentaje.

. Seleccione *Guardar*.




== Suprimir una caché

Si ya no se necesita la caché, es posible eliminarla. Esto elimina la relación de almacenamiento en caché del volumen y elimina la caché de volumen de destino.

.Pasos
. En la navegación de la izquierda de BlueXP, selecciona *Mobility* > *Volume caching*.
. Selecciona una fila y selecciona la opción *Acciones …* a la derecha.
. Seleccione *Eliminar*.
. Marque la casilla.
. Seleccione *Eliminar*.

