---
sidebar: sidebar 
permalink: release-notes/cache-limitations.html 
keywords: volume caching, bluexp 
summary: Las limitaciones conocidas identifican plataformas, dispositivos o funciones que no son compatibles con esta versión del servicio o cuya interoperabilidad con esta no es óptima. 
---
= Limitaciones conocidas
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Las limitaciones conocidas identifican plataformas, dispositivos o funciones que no son compatibles con esta versión del servicio o cuya interoperabilidad con esta no es óptima.



== Limitación al copiar reglas de política de exportación de caché

Las reglas de política de exportación de caché no se copian en el volumen de caché en las siguientes situaciones:

* Cuando el entorno de trabajo del volumen de origen es Amazon FSx para NetApp ONTAP o Cloud Volumes ONTAP, y el volumen de caché es ONTAP 9.10.1 o anterior.
* Cuando el entorno de trabajo del volumen de origen es cualquier versión de ONTAP, y el volumen de caché es ONTAP 9.10.1 o anterior.


Solución alternativa: Debe crear manualmente las reglas para el volumen de caché.



== Error al crear la caché para los equipos virtuales de almacenamiento con el mismo nombre

Si los clústeres de origen y de destino utilizan máquinas virtuales de almacenamiento con el mismo nombre, la caché no se crea.

Solución alternativa: Use nombres distintos para las máquinas virtuales de almacenamiento de origen y de destino.



== Retraso en la visualización de políticas de exportación nuevas o editadas recientemente

Al crear una caché, es posible que no pueda ver una política de exportación creada o editada recientemente en la lista.

Solución alternativa: Vuelva a intentarlo en unos minutos.



== Error en la creación de caché cuando el destino solo tiene el protocolo CIFS habilitado

Se produce un error en la creación de la caché si el clúster de origen o destino tiene ONTAP 9.10.1 o una versión anterior, y el clúster de destino solo tiene el protocolo CIFS habilitado.

Solución alternativa: Utilice un clúster de destino que ejecute ONTAP 9.11.1 o posterior, o con los protocolos CIFS y NFS configurados.
